manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: justussoh
      url-base: https://github.com/justussoh

  projects:
    # - name: zmk
    #   remote: petejohanson
    #   revision: display/bongo-cat-widget

    - name: zmk
      remote: justussoh
      revision: feat/luna
      import: app/west.yml
  self:
    path: config
